newConfig:
    title: Cyclamen Configuration
    rootmenu:
        title: newConfig menu configurator
        config:
            [{ # CONFIG
            varname: NEWCONFIG_VERBOSE,
            type: bool,
            prompt: Increase build verbosity
            }]
        submenu:
            [{ # SUBMENU
            title: Build,
            config:
                [{ # CONFIG
                varname: USE_GCC,
                type: bool,
                prompt: Use a GCC or compatible compiler
                },{ # CONFIG
                varname: CROSS_COMPILE,
                type: string,
                prompt: Cross-compiler tool prefix,
                depends: USE_GCC,
                help: "Same as running make CROSS_COMPILE=prefix- but stored for default make runs in this kernel build directory. You don't need to set this unless you want the configured kernel build directory to select the cross-compiler automatically."
                },{ # CONFIG
                varname: CC,
                type: string,
                prompt: C compiler,
                depends: "!USE_GCC"
                },{ # CONFIG
                varname: AS,
                type: string,
                prompt: Assembler,
                depends: "!USE_GCC"
                },{ # CONFIG
                varname: LD,
                type: string,
                prompt: Linker,
                depends: "!USE_GCC"
                },{ # CONFIG
                varname: AR,
                type: string,
                prompt: Object archiver,
                depends: "!USE_GCC"
                },{ # CONFIG
                varname: MAKE_JOBS,
                type: int,
                prompt: Number of parallel jobs,
                default: 8,
                help: "Argument to pass to -j for make when building the toolchain."
                },{ # CONFIG
                varname: EXTRA_CFLAGS,
                type: string,
                prompt: Extra CFLAGS,
                default: 8,
                help: "Extra compiler options for C code."
                }]

            },{ # SUBMENU
            separator: "-"
            },{ # SUBMENU
            title: "Target",
            config:
                [{ # CONFIG
                varname: ROM_NATIVE,
                type: bool,
                prompt: ROM native,
                default: true,
                help: "Builds cyclamen as ROM-native, for using it as the boot ROM in a system."
                }],
            include: "./src/arch/nConfig.xml"
            },{ # SUBMENU
            title: Drivers,
            include: "./src/drv/nConfig.xml"
            }]
